### ISSUE TITLE
TypeError: Cannot read property 'delete' of undefined at Object.execute (/root/OrvilleBot/commands/closeIsland.js:21:35)

### ISSUE THREAD

**Issue by tigerplush** [tigerplush/OrvilleBot#9]

**Comment by tigerplush** [comment]
more errors:
UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at RequestHandler.execute (/root/OrvilleBot/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:26625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'get' of undefined
    at Object.execute (/root/OrvilleBot/commands/closeIsland.js:11:50)
    at Client.bot.on.message (/root/OrvilleBot/orville.js:89:39)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/root/OrvilleBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/root/OrvilleBot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
TypeError: Cannot read property 'get' of undefined
    at Object.execute (/root/OrvilleBot/commands/closeIsland.js:11:50)
    at Client.bot.on.message (/root/OrvilleBot/orville.js:89:39)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/root/OrvilleBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/root/OrvilleBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/root/OrvilleBot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
